const DATA=window.DASHBOARD_DATA;const jobs=DATA.jobs;const $=id=>document.getElementById(id);const NS='http://www.w3.org/2000/svg';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function addOptions(id,values){const el=$(id);[...new Set(values)].filter(v=>v&&v!=='未说明').sort((a,b)=>a.localeCompare(b,'zh-CN')).forEach(v=>el.add(new Option(v,v)))}
addOptions('sourceFilter',jobs.map(x=>x.source));addOptions('locationFilter',jobs.map(x=>x.location));addOptions('educationFilter',jobs.map(x=>x.education));$('updatedAt').textContent=DATA.generatedAt;
function filtered(){const s=$('sourceFilter').value,l=$('locationFilter').value,e=$('educationFilter').value,q=$('searchFilter').value.trim().toLowerCase();return jobs.filter(x=>(s==='全部'||x.source===s)&&(l==='全部'||x.location===l)&&(e==='全部'||x.education===e)&&(!q||`${x.title} ${x.company}`.toLowerCase().includes(q)))}
function counts(arr,key,exclude=[]){const m={};arr.forEach(x=>{const v=x[key];if(!exclude.includes(v))m[v]=(m[v]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1])}
function svgEl(tag,attrs={},text=''){const el=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));el.textContent=text;return el}
function svgBox(id){const host=$(id);host.innerHTML='';const svg=svgEl('svg',{viewBox:'0 0 700 290',preserveAspectRatio:'none'});host.append(svg);return svg}
function empty(svg){svg.append(svgEl('text',{x:350,y:145,'text-anchor':'middle',class:'label'},'当前筛选条件下暂无数据'))}
function barChart(id,data,color='#1e6b55'){const svg=svgBox(id);data=data.slice(0,10).reverse();if(!data.length)return empty(svg);const left=100,right=35,top=8,row=27,max=Math.max(...data.map(d=>d[1]));data.forEach((d,i)=>{const y=top+i*row,w=(d[1]/max)*(700-left-right);svg.append(svgEl('text',{x:left-8,y:y+17,'text-anchor':'end',class:'label'},d[0].length>7?d[0].slice(0,7)+'…':d[0]));svg.append(svgEl('rect',{x:left,y:y+4,width:w,height:18,rx:2,fill:color}));svg.append(svgEl('text',{x:left+w+7,y:y+17,class:'value'},d[1].toLocaleString()))})}
function salaryChart(arr){const labels=['5千以下','5-10千','10-15千','15-20千','20-30千','30-50千','50千以上'],bins=[0,5,10,15,20,30,50,Infinity],vals=Array(7).fill(0);arr.filter(x=>x.salary>0).forEach(x=>{for(let i=0;i<7;i++)if(x.salary>=bins[i]&&x.salary<bins[i+1]){vals[i]++;break}});const svg=svgBox('salaryChart'),max=Math.max(...vals,1),base=245;vals.forEach((v,i)=>{const x=45+i*90,h=v/max*205;svg.append(svgEl('rect',{x,y:base-h,width:55,height:h,rx:2,fill:i===1?'#1e6b55':'#70b89e'}));svg.append(svgEl('text',{x:x+27,y:base+18,'text-anchor':'middle',class:'label'},labels[i]));svg.append(svgEl('text',{x:x+27,y:base-h-6,'text-anchor':'middle',class:'value'},v))})}
function donut(id,data){const svg=svgBox(id);data=data.slice(0,5);const total=data.reduce((s,d)=>s+d[1],0);if(!total)return empty(svg);const colors=['#1e6b55','#70b89e','#c9993c','#397a9e','#b75d52'],cx=205,cy=145,r=88,circ=2*Math.PI*r;let offset=0;data.forEach((d,i)=>{const len=d[1]/total*circ;svg.append(svgEl('circle',{cx,cy,r,fill:'none',stroke:colors[i], 'stroke-width':34,'stroke-dasharray':`${len} ${circ-len}`,'stroke-dashoffset':-offset,transform:`rotate(-90 ${cx} ${cy})`}));offset+=len;svg.append(svgEl('rect',{x:365,y:58+i*38,width:11,height:11,rx:2,fill:colors[i]}));svg.append(svgEl('text',{x:384,y:68+i*38,class:'label'},`${d[0]}  ${Math.round(d[1]/total*100)}%`))});svg.append(svgEl('text',{x:cx,y:139,'text-anchor':'middle',class:'value'},total.toLocaleString()));svg.append(svgEl('text',{x:cx,y:158,'text-anchor':'middle',class:'label'},'岗位'))}
function bubble(arr){const grouped={};arr.filter(x=>x.location!=='未说明'&&x.salary>0).forEach(x=>{const g=grouped[x.location]||(grouped[x.location]={n:0,sum:0});g.n++;g.sum+=x.salary});let data=Object.entries(grouped).map(([k,v])=>[k,v.n,v.sum/v.n]).sort((a,b)=>b[1]-a[1]).slice(0,14);const svg=svgBox('bubbleChart');if(!data.length)return empty(svg);const maxN=Math.max(...data.map(d=>d[1])),minS=Math.min(...data.map(d=>d[2])),maxS=Math.max(...data.map(d=>d[2]));data.forEach((d,i)=>{const x=55+d[1]/maxN*590,y=245-(d[2]-minS)/(maxS-minS||1)*195,r=7+Math.sqrt(d[1]/maxN)*21;svg.append(svgEl('circle',{cx:x,cy:y,r,fill:'#70b89e',opacity:.65,stroke:'#1e6b55'}));svg.append(svgEl('text',{x:x+r+3,y:y+4,class:'label'},d[0]))});svg.append(svgEl('text',{x:350,y:282,'text-anchor':'middle',class:'label'},'岗位数量 →'));svg.append(svgEl('text',{x:14,y:145,transform:'rotate(-90 14 145)','text-anchor':'middle',class:'label'},'平均月薪 →'))}
function modelChart(){const svg=svgBox('modelChart'),data=DATA.metrics,max=1,colors=['#1e6b55','#70b89e','#c9993c','#397a9e'];data.forEach((d,i)=>{const y=30+i*60,w=d.f1/max*470;svg.append(svgEl('text',{x:10,y:y+18,class:'label'},d.model));svg.append(svgEl('rect',{x:130,y:y,width:470,height:22,rx:3,fill:'#edf1ef'}));svg.append(svgEl('rect',{x:130,y:y,width:w,height:22,rx:3,fill:colors[i]}));svg.append(svgEl('text',{x:610,y:y+16,class:'value'},`${(d.f1*100).toFixed(2)}%`))});svg.append(svgEl('text',{x:130,y:274,class:'label'},'指标：F1 分数'))}
function update(){const arr=filtered(),salaries=arr.filter(x=>x.salary>0).map(x=>x.salary),locs=new Set(arr.map(x=>x.location).filter(x=>x!=='未说明'));$('jobCount').textContent=arr.length.toLocaleString();$('coverage').textContent=`占全部样本 ${(arr.length/jobs.length*100).toFixed(1)}%`;$('avgSalary').textContent=salaries.length?`${(salaries.reduce((a,b)=>a+b,0)/salaries.length).toFixed(1)}千`:'--';$('qualityRate').textContent=arr.length?`${(arr.filter(x=>x.label===1).length/arr.length*100).toFixed(1)}%`:'0%';$('locationCount').textContent=locs.size;barChart('locationChart',counts(arr,'location',['未说明']));salaryChart(arr);donut('educationChart',counts(arr,'education',['未说明']));barChart('categoryChart',counts(arr,'category',['未标注']),'#397a9e');bubble(arr);modelChart();const top=[...arr].sort((a,b)=>b.quality-a.quality).slice(0,12);$('tableCount').textContent=`${arr.length.toLocaleString()} 条`;$('jobTable').innerHTML=top.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.company)}</td><td>${esc(x.location)}</td><td>${esc(x.education)}</td><td>${x.salary?x.salary.toFixed(1)+' 千':'未公布'}</td><td>${x.quality.toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="6">当前筛选条件下暂无岗位</td></tr>'}
['sourceFilter','locationFilter','educationFilter'].forEach(id=>$(id).addEventListener('change',update));$('searchFilter').addEventListener('input',update);$('resetButton').addEventListener('click',()=>{['sourceFilter','locationFilter','educationFilter'].forEach(id=>$(id).value='全部');$('searchFilter').value='';update()});update();
